games_and_blog/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'magic_ball' => 'magic_ball#result'

  get 'guess_secret_number' => 'secret_number#guess'
  post 'secret_number_results/:guess' => 'secret_number#result', :as => "secret_number_results"

  get 'rock_paper_scissors' => 'rock_paper_scissors#throw'
  post 'rock_paper_scissors_results/:throw' => 'rock_paper_scissors#result', :as => "rock_paper_scissors_results"

  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

end

games_and_blog/app/models/concerns/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

games_and_blog/app/models/concerns/post.rb
class Post < ActiveRecord::Base
  has_many :comments

  validates :title, presence: true
end

games_and_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

games_and_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    # is like this
    # @comment = Comment.new
    # @comment.post_id = @post.id

    if !@comment.save
      flash[:error] = "Comment failed to save."
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post

    if !@comment.destroy
      flash[:error] = "Comment failed to delete"
    else
      redirect_to post_path(:id => @post.id) # or root_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

games_and_blog/app/controllers/magic_ball_controller.rb
class MagicBallController < ApplicationController

  def result
    @magic_answer = generate_random_response
    p generate_random_response
    p @magic_answer
  end

  private
  def generate_random_response
    all_responses = [
      "LGTM",
      "SGTM",
      "I hope this works",
      "Oh! Its working!",
      "Chum liao chum liao"
    ]
    all_responses.sample # selects a random answer
  end
end

games_and_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) #post_params is a hash-like object
    if @post.save
      flash[:error] = "" # by right, you don't even need to write this
      redirect_to(post_path(@post.id))
    else # for example if post doesnt have a title
      flash[:error] = "There was a problem trying to create the post! #{@post.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to(post_path(@post.id))
    else
      render :edit
      flash[:error] = "There was a problem trying to update the post! #{@post.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path # or root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

games_and_blog/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController

  def throw
    # render HTML
  end

  def result
    @computer_move = computer_move
    @result = params[:throw].to_i == @computer_move
  end

  private
  def computer_move
    ["rock", "paper", "scissors"].sample
  end

end

games_and_blog/app/controllers/secret_number_controller.rb
class SecretNumberController < ApplicationController

  def guess
    # render HTML
  end

  def result
    # params[:guess] is a string
    @random_num = generate_secret_number
    @result = params[:guess].to_i == @random_num
  end

  private
  def generate_secret_number
    rand(0..10) # it can be a random number here
  end

end

games_and_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

games_and_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

games_and_blog/app/views/magic_ball/result.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Result</title>
  </head>
  <body>
    <%= form_tag(magic_ball_path, method: :get) do %>
      <%= text_field_tag :question, nil, placeholder: "Want to see the future?" %>
      <%= submit_tag "Ask Away" %>
    <% end %>
    <p>
      You asked: <%= params[:question] || "Nothing" %>
    </p>
    <% if params[:question].present? %>
    <%= image_tag "magic_ball.jpg" %>
    <h1>The Magic 8 Ball Says...</h1>
    <p>
      <%= @magic_answer %>
    </p>
    <% end %>
  </body>
</html>

games_and_blog/app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= form_for @post, url: post_path, method: :put do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

games_and_blog/app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>This is tough!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <h2>Games</h2>
    <%= link_to "Magic Ball", magic_ball_path %>
    <%= link_to "Secret Number", guess_secret_number_path %>
    <%= link_to "Rock Paper Scissors", rock_paper_scissors_path %>

    <h2>Blog</h2>
    <%= link_to "New Post", new_post_path %>
    <% @posts.reverse_each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "See More", post_path(post.id) %>
    <% end %>
  </body>
</html>

games_and_blog/app/views/posts/new.html.erb
<h3>New Post</h3>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

games_and_blog/app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>

<%= link_to "Back to all posts", posts_path %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete %>

<hr>

<% @post.comments.each do |comment| %>
  <div class="comment">
    <%= comment.body %>
  </div>
  <div class="author">
    <%= %>
  </div>
  <%= link_to "Delete", post_comment_path(:post_id => @post.id, :id => comment.id), :method => :delete %>
<% end %>

<%= form_for Comment.new, :url => post_comments_path(:post_id => @post.id) do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "Create New Comment" %>
<% end %>

games_and_blog/app/views/rock_paper_scissors/result.html.erb
<p>
  Your move is <%= params[:throw] %>
</p>

<% if @result %>
  <p>
     Your guess the correct secret number!
  </p>
<% else %>
  <p>
    Oh no.. you guess wrongly
  </p>
  <p>
    <%= "The random number is #{@random_num}" %>
  </p>
<% end %>
<%= link_to "Back", guess_secret_number_path %>

games_and_blog/app/views/rock_paper_scissors/throw.html.erb
<p>Choose your move:</p>

<%= link_to "Rock", rock_paper_scissors_results_path(:throw => "rock"), method: :post %>
<%= link_to "Paper", rock_paper_scissors_results_path(:throw => "paper"), method: :post %>
<%= link_to "Scissors", rock_paper_scissors_results_path(:throw => "scissors"), method: :post %>

games_and_blog/app/views/secret_number/guess.html.erb
<h1>My guess is:</h1>

<!-- We want to generate links here -->
<% 11.times do |i| %>
  <%= link_to "Guess #{i}", secret_number_results_path(guess: i), method: :post %>
<% end %>

games_and_blog/app/views/secret_number/result.html.erb
<p>
  Your guess <%= params[:guess] %>
</p>

<% if @result %>
  <p>
     You guessed the secret number correctly :^)
  </p>
<% else %>
  <p>
    Oh no.. your guess is wrong :^(
  </p>
  <p>
    <%= "The random number is #{@random_num}" %>
  </p>
<% end %>
<%= link_to "Back", guess_secret_number_path %>